### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by txdxichen** [robillardstudio/laion2B-en-aesthetic-minified#1]
May I ask why there is a prompt after downloading the git repository that the compressed file is damaged

**Comment by robillardstudio** [comment]
Hey there, I downloaded the zip on my Windows, using Winrar, no trouble here. I also had a dozen of students unzipping on different systems, without reporting any problem. I guess there has been some issue during your downloading.

**Comment by txdxichen** [comment]
Thank you, I think there may be a problem with my network connection
